apiVersion: v1
kind: Service
metadata:
  name: astra-mds
  namespace: astrastorage
  labels:
    app.kubernetes.io/name: astra-mds
    app.kubernetes.io/component: metadata-service
    app.kubernetes.io/part-of: astrastorage
spec:
  selector:
    app.kubernetes.io/name: astra-mds
    app.kubernetes.io/part-of: astrastorage
  ports:
    - name: http
      port: 8080
      targetPort: http
