apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: astra-gateway
  namespace: astrastorage
  labels:
    app.kubernetes.io/name: astra-gateway
    app.kubernetes.io/part-of: astrastorage
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: astra-gateway
      app.kubernetes.io/part-of: astrastorage
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
