// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mds.proto

package grpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetadataServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	CreateDirectory(ctx context.Context, in *CreateDirectoryRequest, opts ...grpc.CallOption) (*CreateDirectoryResponse, error)
	CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error)
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	HeartbeatNode(ctx context.Context, in *HeartbeatNodeRequest, opts ...grpc.CallOption) (*HeartbeatNodeResponse, error)
	AllocateUploadTargets(ctx context.Context, in *AllocateUploadTargetsRequest, opts ...grpc.CallOption) (*AllocateUploadTargetsResponse, error)
	StartUpload(ctx context.Context, in *StartUploadRequest, opts ...grpc.CallOption) (*StartUploadResponse, error)
	CommitChunk(ctx context.Context, in *CommitChunkRequest, opts ...grpc.CallOption) (*CommitChunkResponse, error)
	CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error)
	VerifyUpload(ctx context.Context, in *VerifyUploadRequest, opts ...grpc.CallOption) (*VerifyUploadResponse, error)
	FailUploadVerification(ctx context.Context, in *FailUploadVerificationRequest, opts ...grpc.CallOption) (*FailUploadVerificationResponse, error)
	RetryUpload(ctx context.Context, in *RetryUploadRequest, opts ...grpc.CallOption) (*RetryUploadResponse, error)
	RenameInode(ctx context.Context, in *RenameInodeRequest, opts ...grpc.CallOption) (*RenameInodeResponse, error)
	MoveInode(ctx context.Context, in *MoveInodeRequest, opts ...grpc.CallOption) (*MoveInodeResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	DeleteDirectory(ctx context.Context, in *DeleteDirectoryRequest, opts ...grpc.CallOption) (*DeleteDirectoryResponse, error)
	GetInode(ctx context.Context, in *GetInodeRequest, opts ...grpc.CallOption) (*GetInodeResponse, error)
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	ListChildren(ctx context.Context, in *ListChildrenRequest, opts ...grpc.CallOption) (*ListChildrenResponse, error)
	ListFileChunks(ctx context.Context, in *ListFileChunksRequest, opts ...grpc.CallOption) (*ListFileChunksResponse, error)
	GetUploadSession(ctx context.Context, in *GetUploadSessionRequest, opts ...grpc.CallOption) (*GetUploadSessionResponse, error)
	BuildDownloadPlan(ctx context.Context, in *BuildDownloadPlanRequest, opts ...grpc.CallOption) (*BuildDownloadPlanResponse, error)
}

type metadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataServiceClient(cc grpc.ClientConnInterface) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) CreateDirectory(ctx context.Context, in *CreateDirectoryRequest, opts ...grpc.CallOption) (*CreateDirectoryResponse, error) {
	out := new(CreateDirectoryResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/CreateDirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error) {
	out := new(CreateFileResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/CreateFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/RegisterNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) HeartbeatNode(ctx context.Context, in *HeartbeatNodeRequest, opts ...grpc.CallOption) (*HeartbeatNodeResponse, error) {
	out := new(HeartbeatNodeResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/HeartbeatNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) AllocateUploadTargets(ctx context.Context, in *AllocateUploadTargetsRequest, opts ...grpc.CallOption) (*AllocateUploadTargetsResponse, error) {
	out := new(AllocateUploadTargetsResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/AllocateUploadTargets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) StartUpload(ctx context.Context, in *StartUploadRequest, opts ...grpc.CallOption) (*StartUploadResponse, error) {
	out := new(StartUploadResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/StartUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) CommitChunk(ctx context.Context, in *CommitChunkRequest, opts ...grpc.CallOption) (*CommitChunkResponse, error) {
	out := new(CommitChunkResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/CommitChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error) {
	out := new(CompleteUploadResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/CompleteUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) VerifyUpload(ctx context.Context, in *VerifyUploadRequest, opts ...grpc.CallOption) (*VerifyUploadResponse, error) {
	out := new(VerifyUploadResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/VerifyUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) FailUploadVerification(ctx context.Context, in *FailUploadVerificationRequest, opts ...grpc.CallOption) (*FailUploadVerificationResponse, error) {
	out := new(FailUploadVerificationResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/FailUploadVerification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) RetryUpload(ctx context.Context, in *RetryUploadRequest, opts ...grpc.CallOption) (*RetryUploadResponse, error) {
	out := new(RetryUploadResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/RetryUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) RenameInode(ctx context.Context, in *RenameInodeRequest, opts ...grpc.CallOption) (*RenameInodeResponse, error) {
	out := new(RenameInodeResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/RenameInode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) MoveInode(ctx context.Context, in *MoveInodeRequest, opts ...grpc.CallOption) (*MoveInodeResponse, error) {
	out := new(MoveInodeResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/MoveInode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) DeleteDirectory(ctx context.Context, in *DeleteDirectoryRequest, opts ...grpc.CallOption) (*DeleteDirectoryResponse, error) {
	out := new(DeleteDirectoryResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/DeleteDirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetInode(ctx context.Context, in *GetInodeRequest, opts ...grpc.CallOption) (*GetInodeResponse, error) {
	out := new(GetInodeResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/GetInode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/GetFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) ListChildren(ctx context.Context, in *ListChildrenRequest, opts ...grpc.CallOption) (*ListChildrenResponse, error) {
	out := new(ListChildrenResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/ListChildren", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) ListFileChunks(ctx context.Context, in *ListFileChunksRequest, opts ...grpc.CallOption) (*ListFileChunksResponse, error) {
	out := new(ListFileChunksResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/ListFileChunks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetUploadSession(ctx context.Context, in *GetUploadSessionRequest, opts ...grpc.CallOption) (*GetUploadSessionResponse, error) {
	out := new(GetUploadSessionResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/GetUploadSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) BuildDownloadPlan(ctx context.Context, in *BuildDownloadPlanRequest, opts ...grpc.CallOption) (*BuildDownloadPlanResponse, error) {
	out := new(BuildDownloadPlanResponse)
	err := c.cc.Invoke(ctx, "/astrastorage.mds.v1.MetadataService/BuildDownloadPlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
// All implementations must embed UnimplementedMetadataServiceServer
// for forward compatibility
type MetadataServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	CreateDirectory(context.Context, *CreateDirectoryRequest) (*CreateDirectoryResponse, error)
	CreateFile(context.Context, *CreateFileRequest) (*CreateFileResponse, error)
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	HeartbeatNode(context.Context, *HeartbeatNodeRequest) (*HeartbeatNodeResponse, error)
	AllocateUploadTargets(context.Context, *AllocateUploadTargetsRequest) (*AllocateUploadTargetsResponse, error)
	StartUpload(context.Context, *StartUploadRequest) (*StartUploadResponse, error)
	CommitChunk(context.Context, *CommitChunkRequest) (*CommitChunkResponse, error)
	CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadResponse, error)
	VerifyUpload(context.Context, *VerifyUploadRequest) (*VerifyUploadResponse, error)
	FailUploadVerification(context.Context, *FailUploadVerificationRequest) (*FailUploadVerificationResponse, error)
	RetryUpload(context.Context, *RetryUploadRequest) (*RetryUploadResponse, error)
	RenameInode(context.Context, *RenameInodeRequest) (*RenameInodeResponse, error)
	MoveInode(context.Context, *MoveInodeRequest) (*MoveInodeResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	DeleteDirectory(context.Context, *DeleteDirectoryRequest) (*DeleteDirectoryResponse, error)
	GetInode(context.Context, *GetInodeRequest) (*GetInodeResponse, error)
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	ListChildren(context.Context, *ListChildrenRequest) (*ListChildrenResponse, error)
	ListFileChunks(context.Context, *ListFileChunksRequest) (*ListFileChunksResponse, error)
	GetUploadSession(context.Context, *GetUploadSessionRequest) (*GetUploadSessionResponse, error)
	BuildDownloadPlan(context.Context, *BuildDownloadPlanRequest) (*BuildDownloadPlanResponse, error)
	mustEmbedUnimplementedMetadataServiceServer()
}

// UnimplementedMetadataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMetadataServiceServer struct {
}

func (UnimplementedMetadataServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMetadataServiceServer) CreateDirectory(context.Context, *CreateDirectoryRequest) (*CreateDirectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDirectory not implemented")
}
func (UnimplementedMetadataServiceServer) CreateFile(context.Context, *CreateFileRequest) (*CreateFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFile not implemented")
}
func (UnimplementedMetadataServiceServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedMetadataServiceServer) HeartbeatNode(context.Context, *HeartbeatNodeRequest) (*HeartbeatNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartbeatNode not implemented")
}
func (UnimplementedMetadataServiceServer) AllocateUploadTargets(context.Context, *AllocateUploadTargetsRequest) (*AllocateUploadTargetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateUploadTargets not implemented")
}
func (UnimplementedMetadataServiceServer) StartUpload(context.Context, *StartUploadRequest) (*StartUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartUpload not implemented")
}
func (UnimplementedMetadataServiceServer) CommitChunk(context.Context, *CommitChunkRequest) (*CommitChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitChunk not implemented")
}
func (UnimplementedMetadataServiceServer) CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteUpload not implemented")
}
func (UnimplementedMetadataServiceServer) VerifyUpload(context.Context, *VerifyUploadRequest) (*VerifyUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUpload not implemented")
}
func (UnimplementedMetadataServiceServer) FailUploadVerification(context.Context, *FailUploadVerificationRequest) (*FailUploadVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FailUploadVerification not implemented")
}
func (UnimplementedMetadataServiceServer) RetryUpload(context.Context, *RetryUploadRequest) (*RetryUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryUpload not implemented")
}
func (UnimplementedMetadataServiceServer) RenameInode(context.Context, *RenameInodeRequest) (*RenameInodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameInode not implemented")
}
func (UnimplementedMetadataServiceServer) MoveInode(context.Context, *MoveInodeRequest) (*MoveInodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveInode not implemented")
}
func (UnimplementedMetadataServiceServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedMetadataServiceServer) DeleteDirectory(context.Context, *DeleteDirectoryRequest) (*DeleteDirectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDirectory not implemented")
}
func (UnimplementedMetadataServiceServer) GetInode(context.Context, *GetInodeRequest) (*GetInodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInode not implemented")
}
func (UnimplementedMetadataServiceServer) GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedMetadataServiceServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedMetadataServiceServer) ListChildren(context.Context, *ListChildrenRequest) (*ListChildrenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChildren not implemented")
}
func (UnimplementedMetadataServiceServer) ListFileChunks(context.Context, *ListFileChunksRequest) (*ListFileChunksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFileChunks not implemented")
}
func (UnimplementedMetadataServiceServer) GetUploadSession(context.Context, *GetUploadSessionRequest) (*GetUploadSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadSession not implemented")
}
func (UnimplementedMetadataServiceServer) BuildDownloadPlan(context.Context, *BuildDownloadPlanRequest) (*BuildDownloadPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildDownloadPlan not implemented")
}
func (UnimplementedMetadataServiceServer) mustEmbedUnimplementedMetadataServiceServer() {}

// UnsafeMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataServiceServer will
// result in compilation errors.
type UnsafeMetadataServiceServer interface {
	mustEmbedUnimplementedMetadataServiceServer()
}

func RegisterMetadataServiceServer(s grpc.ServiceRegistrar, srv MetadataServiceServer) {
	s.RegisterService(&MetadataService_ServiceDesc, srv)
}

func _MetadataService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_CreateDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).CreateDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/CreateDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).CreateDirectory(ctx, req.(*CreateDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_CreateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).CreateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/CreateFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).CreateFile(ctx, req.(*CreateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/RegisterNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_HeartbeatNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).HeartbeatNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/HeartbeatNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).HeartbeatNode(ctx, req.(*HeartbeatNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_AllocateUploadTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateUploadTargetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).AllocateUploadTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/AllocateUploadTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).AllocateUploadTargets(ctx, req.(*AllocateUploadTargetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_StartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).StartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/StartUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).StartUpload(ctx, req.(*StartUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_CommitChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).CommitChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/CommitChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).CommitChunk(ctx, req.(*CommitChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_CompleteUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).CompleteUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/CompleteUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).CompleteUpload(ctx, req.(*CompleteUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_VerifyUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).VerifyUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/VerifyUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).VerifyUpload(ctx, req.(*VerifyUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_FailUploadVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailUploadVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).FailUploadVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/FailUploadVerification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).FailUploadVerification(ctx, req.(*FailUploadVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_RetryUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).RetryUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/RetryUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).RetryUpload(ctx, req.(*RetryUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_RenameInode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameInodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).RenameInode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/RenameInode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).RenameInode(ctx, req.(*RenameInodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_MoveInode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveInodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).MoveInode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/MoveInode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).MoveInode(ctx, req.(*MoveInodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_DeleteDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).DeleteDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/DeleteDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).DeleteDirectory(ctx, req.(*DeleteDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetInode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetInode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/GetInode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetInode(ctx, req.(*GetInodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_ListChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChildrenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ListChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/ListChildren",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ListChildren(ctx, req.(*ListChildrenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_ListFileChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFileChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ListFileChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/ListFileChunks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ListFileChunks(ctx, req.(*ListFileChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetUploadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetUploadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/GetUploadSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetUploadSession(ctx, req.(*GetUploadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_BuildDownloadPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildDownloadPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).BuildDownloadPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/astrastorage.mds.v1.MetadataService/BuildDownloadPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).BuildDownloadPlan(ctx, req.(*BuildDownloadPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataService_ServiceDesc is the grpc.ServiceDesc for MetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "astrastorage.mds.v1.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _MetadataService_Health_Handler,
		},
		{
			MethodName: "CreateDirectory",
			Handler:    _MetadataService_CreateDirectory_Handler,
		},
		{
			MethodName: "CreateFile",
			Handler:    _MetadataService_CreateFile_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _MetadataService_RegisterNode_Handler,
		},
		{
			MethodName: "HeartbeatNode",
			Handler:    _MetadataService_HeartbeatNode_Handler,
		},
		{
			MethodName: "AllocateUploadTargets",
			Handler:    _MetadataService_AllocateUploadTargets_Handler,
		},
		{
			MethodName: "StartUpload",
			Handler:    _MetadataService_StartUpload_Handler,
		},
		{
			MethodName: "CommitChunk",
			Handler:    _MetadataService_CommitChunk_Handler,
		},
		{
			MethodName: "CompleteUpload",
			Handler:    _MetadataService_CompleteUpload_Handler,
		},
		{
			MethodName: "VerifyUpload",
			Handler:    _MetadataService_VerifyUpload_Handler,
		},
		{
			MethodName: "FailUploadVerification",
			Handler:    _MetadataService_FailUploadVerification_Handler,
		},
		{
			MethodName: "RetryUpload",
			Handler:    _MetadataService_RetryUpload_Handler,
		},
		{
			MethodName: "RenameInode",
			Handler:    _MetadataService_RenameInode_Handler,
		},
		{
			MethodName: "MoveInode",
			Handler:    _MetadataService_MoveInode_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _MetadataService_DeleteFile_Handler,
		},
		{
			MethodName: "DeleteDirectory",
			Handler:    _MetadataService_DeleteDirectory_Handler,
		},
		{
			MethodName: "GetInode",
			Handler:    _MetadataService_GetInode_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _MetadataService_GetFile_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _MetadataService_GetNode_Handler,
		},
		{
			MethodName: "ListChildren",
			Handler:    _MetadataService_ListChildren_Handler,
		},
		{
			MethodName: "ListFileChunks",
			Handler:    _MetadataService_ListFileChunks_Handler,
		},
		{
			MethodName: "GetUploadSession",
			Handler:    _MetadataService_GetUploadSession_Handler,
		},
		{
			MethodName: "BuildDownloadPlan",
			Handler:    _MetadataService_BuildDownloadPlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mds.proto",
}
