listeners.tcp.default = 5672
management.tcp.port = 15672
prometheus.tcp.port = 15692

loopback_users.guest = false
cluster_partition_handling = pause_minority
queue_leader_locator = balanced

cluster_formation.peer_discovery_backend = classic_config
cluster_formation.classic_config.nodes.1 = rabbit@rabbitmq-1
cluster_formation.classic_config.nodes.2 = rabbit@rabbitmq-2
cluster_formation.classic_config.nodes.3 = rabbit@rabbitmq-3
