apiVersion: v1
kind: Service
metadata:
  name: astra-datanode-headless
  namespace: astrastorage
  labels:
    app.kubernetes.io/name: astra-datanode
    app.kubernetes.io/component: datanode
    app.kubernetes.io/part-of: astrastorage
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: astra-datanode
    app.kubernetes.io/part-of: astrastorage
  ports:
    - name: http
      port: 10080
      targetPort: http
