apiVersion: v1
kind: ConfigMap
metadata:
  name: astra-postgres-config
  namespace: astrastorage
  labels:
    app.kubernetes.io/name: astra-postgres
    app.kubernetes.io/component: metadata-database
    app.kubernetes.io/part-of: astrastorage
data:
  POSTGRES_DB: astra
  PGDATA: /var/lib/postgresql/data/pgdata
  MDS_POSTGRES_MAX_CONNS: "8"
  MDS_POSTGRES_MIN_CONNS: "1"
  MDS_POSTGRES_CONNECT_TIMEOUT: 5s
