apiVersion: v1
kind: Secret
metadata:
  name: astra-postgres
  namespace: astrastorage
  labels:
    app.kubernetes.io/name: astra-postgres
    app.kubernetes.io/component: metadata-database
    app.kubernetes.io/part-of: astrastorage
type: Opaque
stringData:
  username: astra
  password: astra-dev
  mds-postgres-dsn: postgres://astra:astra-dev@astra-postgres.astrastorage.svc.cluster.local:5432/astra?sslmode=disable
